### ISSUE TITLE
ueno gatsby starter error 

### ISSUE THREAD

**Issue by jonniebigodes** [ueno-llc/ueno-gatsby-starter#4] opened 2019-02-22 01:49 UTC
While trying to resolve a issue that was created in the gatsby github repo. more specifically starting from [this](https://github.com/gatsbyjs/gatsby/issues/10712#issuecomment-466116529) comment, led me to install the starter to further check what could be causing the issue in that case. I followed the instructions  in the readme. It all went fine. Issuing `gatsby develop` went without a hitch. The only change i've made to the code is related to the links as stated in the documentation, as i'm using it with Gatsby.

Now the problem is that when i open up a browser to `http://localhost:8000`. I'm presented with the following:
![ueno_1](https://user-images.githubusercontent.com/22988955/53214037-feacf500-3642-11e9-9afa-c26c25528800.png)
![ueno_2](https://user-images.githubusercontent.com/22988955/53214039-01a7e580-3643-11e9-9436-0d7ea39eccfb.png)
![ueno_3](https://user-images.githubusercontent.com/22988955/53214041-04a2d600-3643-11e9-8775-e7e0c4379192.png)
![ueno_4](https://user-images.githubusercontent.com/22988955/53214050-08365d00-3643-11e9-9c91-8799ec41ba56.png)

I did not have the time to further investigate what could be the issue and/or culprit here. But before that i though to reach out and ask if are there any more specific steps needed to get the site running in development mode? If not, if only thing needed is issuing `gatsby develop` can anyone shed some insights on what might be the problem here?

Thanks in advance.
Feel free to provide feedback

**Comment by birkir** [comment] 2019-02-22 10:08
Hey @jonniebigodes 

How did you init the project?

Using the `create-ueno-app` or by using `gatsby new ueno-test "https://github.com/ueno-llc/ueno-gatsby-starter#master --recursive"`?

Both works fine for me with all commands `yarn dev`, `gatsby develop` and `gatsby build`.

**Comment by birkir** [comment] 2019-02-22 10:10
Did you by any chance move the svg files or project source files?

We have a plugin in gatsby-config called `gatsby-plugin-react-svg` that only works with SVG files from the folder `./src/assets/svg`.

**Comment by jonniebigodes** [comment] 2019-02-22 14:58
@birkir started with the `gatsby new ueno-test "https://github.com/ueno-llc/ueno-gatsby-starter#master --recursive` issuing `gatsby develop` opening the browser window led me to the error. 
So i deleted the folder with the site and went with the `create-ueno-app` approach. Same effect.
And the only change i've made like i said in the earlier comment was i've adjusted the code to gatsby links as per documentation.

**Comment by jeremybarbet** [comment] 2019-02-22 16:01
Hey @jonniebigodes,

I'm able to reproduce this issue under Windows. I'll dig in to see where does it comes from.

**Comment by jonniebigodes** [comment] 2019-02-22 16:23
@jeremybarbet thank you so much for the time and sorry for not mentioning earlier in the issue description that i was running the starter in windows.

**Comment by jeremybarbet** [comment] 2019-02-22 16:36
No problem.

It seems like this it's related to https://github.com/jacobmischka/gatsby-plugin-react-svg. I've been trying another plugin and it works on windows, but the import syntax is a bit different, we will keep looking for a better alternative.

**Comment by jeremybarbet** [comment] 2019-02-25 11:28
Alright, seems like the issue is fixed with that: https://github.com/ueno-llc/ueno-gatsby-starter/commit/7eecd4384321df6557f31eb5f66cb5bb27001637

Thanks for the report :)

**Closed as completed by jeremybarbet** 2019-02-25 11:28 UTC

**Comment by jonniebigodes** [comment] 2019-02-25 15:14
@jeremybarbet thank you once more for the feedback and resolution of the issue.
